### ISSUE TITLE
Update Uploading ETA with value from progress bar tooltip

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#116]
In the Uploading state, update the ETA with value from progress bar mouse-over tooltip:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/61453d94-a8de-42ef-91e1-096641ee365a)

**Comment by jcoffland** [comment]
These are already the same value.  I believe the problem here is that if you mouse over and trigger a tooltip the value of the tooltip will not change unless you close and reopen the tooltip.  So in this case, the ETA was 10 secs when you first moused over the progress bar.  In the code, the same variable is used in both cases.
