### ISSUE TITLE
Add TPF benchmarking page like in HFM

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-web-client-bastet#153]
![hfm-benchmark](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/1166284/d5cd7392-e501-46b0-9340-3969394f5a06)

The benchmark page shows an average of measured frame timings by project and for each resource grouping.

**Comment by jcoffland** [comment]
See also https://github.com/FoldingAtHome/fah-client-bastet/issues/86

**Comment by muziqaz** [comment]
For clarification, on the left there is a list of already completed or currently running projects. Any other projects which have not been downloaded and processed by that user do not need to be there.
The project info at the bottom of the screenshot is not essential, however it is very very helpful and informative for a quick troubleshooting or decision making when testing.

**Comment by jcoffland** [comment]
Completed in v8.4.0 alpha.

**Comment by muziqaz** [comment]
Any chance of some sort of filtering?
for example, in log section that search bar works great, and those Erros and Warnings tick boxes are great too. Maybe something similar in Work Units section (filter by project, by CPU or GPU type, by which machine/device finished or did not finish the unit.
Actually now I notice that Work Units history does not show which machine finished that (if possible even split per Resource groups).
Quite often we need to see which machines/devices are failing certain projects.

Export to excel/txt would be great, too, if at all possible
Thanks

P.S.
Question: is the Work Units content saved locally in some specific file, or on the server? I assume it is local, so would be nice to know which file it is being saved in to preserve in case we are formating the PC. (Windows and Linux)
The reason I am assuming history is not saved on the server is because I switched the PCs, and new one does not list units finished on other PC.

**Comment by jcoffland** [comment]
I've added #159 and #160.  These should be a step in the right direction at least.  Maybe we can add searching/filtering as well.

The WU history is stored in ``client.db`` on each client.  If that is deleted then Web Control will no longer have access to this information.

**Comment by jcoffland** [comment]
The clients gather their own information.  Web Control combines it all.
