### ISSUE TITLE
FAH web control is the older one for Windows installs

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#175]
Installing FAH v8.4.3 on Windows gives you the previous FAH web controls & layout with Firefox set as my default browser:
![image](https://github.com/user-attachments/assets/68813e4a-3074-44c9-83a2-bb645dc10d40)
This was installing the v8.4.3 (debug) on top of v8.4.3 (release), and I was logged in to my FAH account on that browser.
Doing a refresh (or refresh without cache) loads the current web controls, so it's not that much of a problem.

Where on Linux Mint with Firefox installs do the desired behavior: the FAH installation does a refresh (or refresh without cache) and loads the current web controls.

**Comment by Hou5e** [comment]
I also get the older FAH web control page from the Windows system control's 'Web Control' menu item. Doing a refresh loads the current web control.

**Comment by jcoffland** [comment]
This is a browser caching issue.  When Web Control sees a local client with a version number newer than it has ever seen before it will store the version number for future reference and then reload the page.  Since you went from  v8.4.3 (debug) to v8.4.3 (release) a reload would not have been triggered.  I'm assuming you installed v8.4.3 (debug) before v8-4.foldingathome.org was updated.  This wont usually happen.
