### ISSUE TITLE
Fix PPD values showing up as zeros in "Work Units" section

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#182]
`Work Units Averages` PPD column values are very inconsistent. A lot of completed projects are showing 0 in PPD column.

**Comment by jcoffland** [comment]
Are these clients running the latest client version?  The WUs may have been logged on an older client.

**Comment by muziqaz** [comment]
I see last assigned 5d ago. This is only one client, which is updated right after new version is released. Not sure when exactly latest alpha dropped.

**Comment by jcoffland** [comment]
Which WU?

**Comment by muziqaz** [comment]
This is in `Work Units Averages`, so
p17939 (5d 20h ago)
p17938
p17937
p17936
p16771 (6d 01h ago)

**Comment by rilian** [comment]
![_s 112](https://github.com/user-attachments/assets/2a92d9c4-10b8-43d9-9b80-f28c45fedcbc)
![_s 113](https://github.com/user-attachments/assets/6316e434-5aba-48c5-bf22-002965904a37)

i'd like to add here, i used 2 GPUs and they worked for about 3 days, then 1 GPU died and was excluded from FAH. Because each GPU requires 1 CPU, and there were 2 CPUs activated, FAH decided that 1 free CPU must be used for CPU folding and therefore tried to load one job.

Even without regards that it did not complete any CPU jobs, this event added 0 CPUs rows to each table under each project

I think items like "0 CPUS" should be ignored

**Comment by kbernhagen** [comment]
I think GPU WUs should always take zero cpus from the resource pool when assigned.
