### ISSUE TITLE
Peers feature is not working

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-web-client-bastet#54]
I take it Peers feature is supposed to allow us to remote monitor other network clients. For a moment it is not working. Might be being blocked by different port settings or something

**Comment by kbernhagen** [comment]
It doesn't work for remote peers because, by default, the client only listens for connections from localhost.

You can change this, but it is a security risk and lets anyone on the network mess with your client.

A ssh tunnel should work well.

**Comment by muziqaz** [comment]
We need at least FAHControl like functionality to monitor either local network or remote clients of our own. A lot of us have farms of computers, which need centralized way of controlling and monitoring.

**Comment by kbernhagen** [comment]
I believe the long term goal is to have a login to app.foldingathome.org, where you could monitor and control all clients configured as you. The clients would make secure connections to the main site server to support this.

**Comment by jcoffland** [comment]
If you have a local network which you control and is protected from the Internet by a firewall then you can configure you v8 clients to listen on an IP address on your local network and then add them as peers.  By default the client is configured with:

    http-addresses=127.0.0.1:7396

This causes it to listen on ``127.0.0.1`` port ``7396`` which makes it only accessible from the localhost.  You could change this by editing the ``config.xml`` to include something like:

    <http-addresses v="192.168.0.2:7396"/>

Where ``192.168.0.2`` is the IP address of the client on your local network.  Then any web frontend with access to that network could add it as a peer.

But, as @kbernhagen mentioned traffic between the web frontend and the client will not be encrypted and anyone on the local network can manipulate the clients on that network.

We have a plan to make the clients all connect to a server at F@H and use that route to enable secure command and control of all your clients but this feature is a ways off yet.

The v7 clients work very similarly but they also have a password feature.  However, it's not very secure since the password is transmitted in the clear over the network.  So, technically v8 works the same and is as secure as v7.  I.e. the network security is up to you.

**Comment by kbernhagen** [comment]
I think you meant

```
<http-addresses v="127.0.0.1:7396 192.168.0.2:7396"/>
```

**Comment by kbernhagen** [comment]
Above does not work for me
```
10:26:41:I1:Listening for HTTP on 127.0.0.1:8396
10:26:41:I1:Listening for HTTP on 192.168.42.71:8396
10:26:41:E :Exception: Could not bind socket to 192.168.42.71:8396: Can't assign requested address
10:26:41:E :       At: src/cbang/socket/SocketDefaultImpl.cpp:238:cb::SocketDefaultImpl::bind()
10:26:41:E :Caught at: /Users/kevin2/fah-dev/workarea/cbang/src/cbang/ApplicationMain.h:59:cb::doApplication()
```

**Comment by kbernhagen** [comment]
This works
```
  <http-addresses v='127.0.0.1:8396 0.0.0.0:8396'/>
  <allow v='127.0.0.1 10.0.0.0/8 192.168.0.0/16 172.16.0.0/12 169.254.0.0/16'/>
  <deny v='0.0.0.0/0'/>
```

**Comment by kbernhagen** [comment]
This works too
```
  <allow v='127.0.0.1 obelisk.local'/>

```

**Comment by kbernhagen** [comment]
Off topic:
Safari seems to work if I copy a built `fah-web-client-bastet/dist` (only 1.8 MiB) to ./web-root and use
```
  <allowed-origins v='https://app.foldingathome.org http://localhost:8396'/>
  <web-root v='web-root'/>
```
and open `http://localhost:8396`

**Comment by jcoffland** [comment]
This should be sufficient:

    <http-addresses v='0.0.0.0:8396'/>

It binds to all IP addresses.

**Comment by kbernhagen** [comment]
This is actually useful:

I can access `http://mytower.local:7396` from my phone or iPad with
```
<allowed-origins v='https://app.foldingathome.org http://localhost:7396 http://mytower.local:7396'/>
<http-addresses v='127.0.0.1:7396 0.0.0.0:7396'/>
<web-root v='/Users/me/fah-web-client-bastet/dist'/>
<allow v='127.0.0.1 192.168.0.0/16'/>
<deny v='0.0.0.0/0'/>
```

I also had to
```
cd ~
git clone https://github.com/foldingathome/fah-web-client-bastet
cd fah-web-client-bastet
```

Apply patch
```
diff --git a/src/client.js b/src/client.js
index 35d3e74..9fa2ad7 100644
--- a/src/client.js
+++ b/src/client.js
@@ -3,7 +3,7 @@ import Sock   from './sock.js'
 import util   from './util.js'
 import Cookie from './cookie.js'
 
-const default_host = '127.0.0.1'
+const default_host = 'mytower.local'
 const default_port = 7396
 const api_url      = 'https://api.foldingathome.org'
 
```

Then
```
npm install
npm run build
```

It doesn't have a mobile-optimized layout, but still works well.

I have `<deny v='0.0.0.0/0'/>` because `<deny v='0/0'/>` was not sufficient with v7.

**Comment by kbernhagen** [comment]
Once that is working, I can access other clients on the lan as peers to the instance on `mytower`.

The other clients just need
```
<http-addresses v='0.0.0.0:7396'/>
<allow v='127.0.0.1 192.168.0.0/16'/>
<deny v='0.0.0.0/0'/>
```

Of course, none of this is secure. Nobody should do this on a laptop, or on an untrusted network.

**Comment by jcoffland** [comment]
I believe this is working.  You just have to configure to allow remote connections on the remote clients.
