### ISSUE TITLE
Support themes

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-web-client-bastet#64]
I would at least like a dark mode.

A possibly useful link for dark mode:
https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

**Comment by blakegearin** [comment]
I would be interested in working on this, but I wasn't able to find documentation on contributing. 

For reference, I regularly work with Vue (albeit Vue 2) in my current full-time position. I also recently finished a [personal project](https://github.com/blakegearin/folding-at-home-in-the-dark-themes#readme) sideloading custom themes for [FAHITD](https://chromewebstore.google.com/detail/folding-at-home-in-the-da/alpjkkbjnbkddolgnicglknicbgfahoe).  

I see from the issues on this repo that this functionality will likely live in `AppSettings.vue` via `/settings` which doesn't exist yet. For working on this, I could create a new component (say `ThemeView.vue`) then either add it to a new, skeleton `AppSettings.vue` or make it directly accessible via a new route like `/themes` (which could later be removed once the app settings component is established).

Thoughts, comments, concerns?

**Comment by jcoffland** [comment]
I want to keep this very simple.  Currently, there are two themes [dark](https://github.com/FoldingAtHome/fah-web-client-bastet/blob/main/src/dark.styl) and [light](https://github.com/FoldingAtHome/fah-web-client-bastet/blob/main/src/light.styl).  The ``dark`` theme actually uses ``light`` as a base theme.

CSS variables are used.  This mostly decouples the themes from the structure of the web app.  Which is important because I want to be able to modify the web app without having to update the themes.

I believe this can be implemented directly in Javascript without anything Vue specific.  There should be a function like ``set_theme(theme)``.  Where ``theme`` is either a path to theme file or even just JSON data describing the theme.  If it's JSON then and we only support modifying the theme by changing CSS variable values then it's just a dictionary of key value pairs.  The nice thing about that is we could easily create a theme editor at some point.

I would add the ability to reference other variables with ``$variable-name``.   The implementation might look like this:

```javascript
function theme_resolve_vars(theme, text) {
  return text.replace(/\$([a-z-]+)/g, (match, name) => theme_resolve_vars(theme, theme[name] || ''))
}

function set_theme(theme) {
  let style = document.querySelector(':root').style

  for (const [key, value] of Object.entries(theme))
    style.setProperty('--' + key, theme_resolve_vars(theme, value))
}
```

The above is untested.

Some themes could be built-in and you could load a custom theme and save it to your account.

The base theme (light) ends up looking like this:

```json
{
  "highlight-color":    "#444",
  "secondary-color":    "#888",

  "error-color":        "#b51100",
  "success-color":      "#4caf50",
  "warn-color":         "#fb0",

  "body-bg":            "#e7e7e7",
  "body-fg":            "#333",

  "header-fg":          "#333",
  "header-bg":          "#fff",

  "input-bg":           "#fff",
  "input-border-color": "#eee",
  "input-border":       "2px inset $input-border-color",

  "panel-bg":           "#fff",
  "panel-fg":           "$body-fg",

  "link-color":         "#ee9322",
  "link-alt":           "#55aaff",

  "logo-color":         "$header-fg",

  "log-fg":             "$panel-fg",
  "log-bg":             "$panel-bg",

  "title-color":        "inherit",
  "subtitle-color":     "$secondary-color",

  "progress-fg":        "#fff",
  "progress-bg":        "#aaa",
  "progress-bar":       "$success-color",
  "progress-band":      "rgba(255, 255, 255, 0.15)",
  "progress-img":       "linear-gradient(45deg, $progress-band 25%, transparent 25%, transparent 50%, $progress-band 50%, $progress-band 75%, transparent 75%, transparent)",

  "button-bg":          "#0b5ed7",
  "button-fg":          "#fff",
  "button-icon-fg":     "#000",
  "button-success":     "$success-color",
  "button-caution":     "$error-color",
  "button-disabled-bg": "#aaa",
  "button-disabled-fg": "#ddd",

  "pacify-bg":          "rgba(0, 0, 0, 0.6)",

  "overlay-bg":         "rgba(0, 0, 0, 0.4)",
  "overlay-fg":         "#fff",

  "code-bg":            "#ddd",
  "code-fg":            "#444",

  "border-color":       "$panel-bg",

  "table-border-color": "#ddd",
  "table-border":       "1px solid $table-border-color",
  "table-header-bg":    "#dedede",
  "table-header-fg":    "#333",
  "table-even":         "#fff",
  "table-odd":          "#f3f3f3",

  "shadow-color":       "#222",
  "shadow":             "3px 3px 12px $shadow-color",

  "border-radius":      "0",

  "border":             "1px solid $border-color",
  "header-border":      "$border"
}
```

**Comment by jcoffland** [comment]
As of v8.4.0 alpha Web Control supports dark/light, wide and compact modes.  At this point does not seem like a good use of resources to offer full blown themes.

**Comment by kbernhagen** [comment]
After using, then deselecting compact mode, the tables have excess height, which is a problem particularly on mobile.

As I try this now, the WU rows are not visible.

Using compact on mobile makes the buttons too close for my fingers.

**Comment by kbernhagen** [comment]
Reset columns to default seems to fix problems.
