### ISSUE TITLE
Show available GPUs/CPUs on the main page

### ISSUE THREAD

**Issue by Josh65-2201** [FoldingAtHome/fah-web-client-bastet#83]
In v7 it would show the all devices as ready when not folding. The interface should also show this under the work units section with the status showing as ready rather than not showing.

**Comment by jcoffland** [comment]
You'll need to explain this a bit more.  I'm not quite sure what you mean.  What is a "device enabled to be [a] work unit"?  Maybe provide some screenshots.

**Comment by Josh-65** [comment]
Like the GPUs and CPUs that can have work units done on them.
![image](https://user-images.githubusercontent.com/26977075/220730692-bcc18e1a-4b0b-4c50-8a22-b9de2ed35860.png)

**Comment by jcoffland** [comment]
Ok, I see your point now.  We currently show the WUs that are active and the resources they are using.  It's different than in the v7 client because we may have WUs that use multiple CPUs and GPUs.

However, I can see the advantage of considering a different approach where instead we show a representation of the available resources (i.e. CPUs and GPUs) and a visualization of how they are being used with the ability to enable/disable their use on the main screen instead of just in the settings.

**Comment by kbernhagen** [comment]
Maybe a placeholder WU would be good?

I find it annoying that a potential WU sometimes appears and disappears as an assignment is negotiated.

**Comment by jcoffland** [comment]
There's not fixed WU slot like in v7.  I think the latest releases strike a good compromise.  The resources are shown and it's no possible to sub divide your machine into resource groups if you really want to.
